name: Frontend Compliance CI

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/**'

defaults:
  run:
    shell: bash
    working-directory: frontend


jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup_node
        with:
          env: 'dev'
      - run: |
          npm ci
          npm run lint

  test:
    needs: linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup_node
        with:
          env: 'dev'

      - name: Run Tests
        run: |
          npm ci
          npm test